name: Release
on:
  push:
    branches: [main]
  workflow_dispatch:
concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions:
  contents: write
  id-token: write
  issues: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'
          check-latest: true
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
